Config = {}

Config.UseBlip = true                      -- [true to enable the blip | false disables the blip]
Config.ItemCheck = false                   -- true for item check / false for no item
Config.Item = 'itemhere'

Config.RequiredItems = {                   -- Items required to interact with the NPC
    "phone",
}

Config.Location = {
    Coords = vector4(283.18, -975.83, 28.43, 293.38),
    ModelName = "a_m_m_farmer_01",
    ModelHash = 0x94562DD7,
    SetBlipSprite = 477,
    SetBlipDisplay = 6,
    SetBlipScale = 0.85,
    SetBlipColour = 12,
    BlipName = "Wholesale Mystery Meat"
}

Config.Icons = {
    EyeIcon = "fa-solid fa-face-smile-horns",
    Header = "fa-solid fa-utensils",
    EatItems = "fa-solid fa-utensils",
    DrinkItems = "fa-solid fa-coffee",
    Alcohol = "fa-solid fa-wine-bottle",
    TacoFood = "fa-solid fa-taco",
    TacoDrinks = "fa-solid fa-taco",
    Ingredients = "fa-solid fa-carrot",
    BurgerShot = "fa-solid fa-hamburger",
    BBQ = "fa-solid fa-drumstick-bite",
    JamaicanDrinks = "fa-solid fa-glass-martini-alt",
    JamaicanFood = "fa-solid fa-pepper-hot",
    McDonalds = "fa-solid fa-mcdonalds"
}

Config.Text = {
    TargetLabel = "Wholesale Mystery Meat",
    PedHeader = "Wholesale Mystery Meat",
    EatItems = "Eat Items",
    DrinkItems = "Drink Items",
    Alcohol = "Alcohol",
    TacoFood = "Taco Food",
    TacoDrinks = "Taco Drinks",
    Ingredients = "Ingredients",
    BurgerShot = "BurgerShot",
    BBQ = "BBQ",
    JamaicanDrinks = "Jamaican Drinks",
    JamaicanFood = "Jamaican Food",
    McDonalds = "McDonalds",
}


Config.EatShop = {
    label = "Eat Items",
    slots = 10,
    items = {
        [1] = {
            name = "tosti",
            price = 50,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "twerks_candy",
            price = 10,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "snikkel_candy",
            price = 10,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "sandwich",
            price = 25,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 4,
        },
    }
}

Config.DrinkShop = {
    label = "Drink Items",
    slots = 10,
    items = {
        [1] = {
            name = "water_bottle",
            price = 15,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "coffee",
            price = 20,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "kurkakola",
            price = 10,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 3,
        },
    }
}

Config.AlcoholShop = {
    label = "Alcohol",
    slots = 10,
    items = {
        [1] = {
            name = "beer",
            price = 30,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "whiskey",
            price = 50,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "vodka",
            price = 50,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "grape",
            price = 5,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "wine",
            price = 60,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "grapejuice",
            price = 10,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 6,
        },
    }
}

Config.TacoFoodShop = {
    label = "Taco Food",
    slots = 10,
    items = {
        [1] = {
            name = "beef-taco",
            price = 30,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "quesadilla",
            price = 25,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "chicken-burrito",
            price = 30,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "nachos",
            price = 20,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 4,
        },
    }
}

Config.TacoDrinksShop = {
    label = "Taco Drinks",
    slots = 10,
    items = {
        [1] = {
            name = "coke-soda",
            price = 10,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "fanta",
            price = 10,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 2,
        },
    }
}

Config.IngredientsShop = {
    label = "Ingredients",
    slots = 10,
    items = {
        [1] = {
            name = "tortillas",
            price = 5,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "ground-beef",
            price = 10,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "cheddar-cheese",
            price = 5,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "butter",
            price = 5,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "chicken",
            price = 10,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "lettuce",
            price = 5,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "tortilla-chips",
            price = 5,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "carbonated-water",
            price = 5,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "sugar-cubes",
            price = 5,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "taco-tomato",
            price = 5,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 10,
        },
    }
}

Config.BurgerShotShop = {
    label = "BurgerShot",
    slots = 10,
    items = {
        [1] = {
            name = "burger-bleeder",
            price = 25,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "burger-moneyshot",
            price = 30,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "burger-torpedo",
            price = 35,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "burger-heartstopper",
            price = 50,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "burger-meatfree",
            price = 20,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "burger-fries",
            price = 15,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "burger-softdrink",
            price = 10,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "burger-mshake",
            price = 10,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "burger-bun",
            price = 5,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "burger-meat",
            price = 10,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 10,
        },
    }
}

Config.BBQShop = {
    label = "BBQ",
    slots = 10,
    items = {
        [1] = {
            name = "burger",
            price = 25,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "raw-burger",
            price = 15,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "chicken-burger",
            price = 20,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "raw-chicken-burger",
            price = 15,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "hotdog",
            price = 10,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "raw-hotdog",
            price = 5,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "ribs",
            price = 35,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "raw-ribs",
            price = 20,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "brisket",
            price = 40,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "raw-brisket",
            price = 25,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 10,
        },
    }
}

Config.JamaicanDrinksShop = {
    label = "Jamaican Drinks",
    slots = 10,
    items = {
        [1] = {
            name = "rum-punch",
            price = 20,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "red-stripe",
            price = 15,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "ginger-beer",
            price = 10,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "supligen",
            price = 20,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 4,
        },
    }
}

Config.JamaicanFoodShop = {
    label = "Jamaican Food",
    slots = 10,
    items = {
        [1] = {
            name = "jerk-chicken",
            price = 30,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "ackee-and-saltfish",
            price = 35,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "curried-goat",
            price = 40,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "oxtail-stew",
            price = 45,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "callaloo",
            price = 25,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "fried-dumpling",
            price = 10,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "ital-stew",
            price = 30,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "veggie-patty",
            price = 15,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 8,
        },
    }
}

Config.McDonaldsShop = {
    label = "McDonalds",
    slots = 20,
    items = {
        [1] = {
            name = "bigmac",
            price = 30,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "mcchicken",
            price = 25,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "quarterpounder",
            price = 35,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "dquarterpounder",
            price = 40,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "filet-o-fish",
            price = 30,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "bigmac_meal",
            price = 50,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "mcchicken_meal",
            price = 45,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "quarterpounder_meal",
            price = 55,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "dquarterpounder_meal",
            price = 60,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "filet-o-fish_meal",
            price = 50,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "cheeseburger",
            price = 20,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "dcheeseburger",
            price = 25,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "tcheeseburger",
            price = 30,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "6pnuggets",
            price = 15,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "10pnuggets",
            price = 25,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "20pnuggets",
            price = 35,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "cheeseburger_meal",
            price = 40,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "dcheeseburger_meal",
            price = 45,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 18,
        },
        [19] = {
            name = "tcheeseburger_meal",
            price = 50,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 19,
        },
        [20] = {
            name = "6pnuggets_meal",
            price = 35,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 20,
        },
        [21] = {
            name = "10pnuggets_meal",
            price = 45,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 21,
        },
        [22] = {
            name = "20pnuggets_meal",
            price = 55,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 22,
        },
        [23] = {
            name = "sfries",
            price = 10,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 23,
        },
        [24] = {
            name = "mfries",
            price = 15,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 24,
        },
        [25] = {
            name = "lfries",
            price = 20,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 25,
        },
        [26] = {
            name = "hotapplepie",
            price = 15,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 26,
        },
        [27] = {
            name = "ssconef",
            price = 10,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 27,
        },
        [28] = {
            name = "sscone",
            price = 8,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 28,
        },
        [29] = {
            name = "mflurryo",
            price = 15,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 29,
        },
        [30] = {
            name = "mflurrym",
            price = 15,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 30,
        },
        [31] = {
            name = "cocacola",
            price = 10,
            amount = 100,
            info = { quality = 100, },
            type = "item",
            slot = 31,
        },
    }
}
